/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casafer.telas;

import casafer.DaoNotasVendas;
import casafer.NotasVendas;
import casafer.Vendedores;
import java.awt.Color;
import java.awt.Component;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public final class Principal extends javax.swing.JFrame {
    
        Color VERMELHO = new Color(231, 76, 60);
        Color CINZA = new Color(127, 140, 141);
        Color VERDE = new Color(46, 204, 113);
        Color AMARELO = new Color(241, 196, 15);
        Color VERMELHO_ES = new Color(22, 160, 133);
    
    public Principal() {
        initComponents();
        iniciaTela();
        
        
        
        java.util.Timer timer = new java.util.Timer();
        timer.schedule(new Principal.botaoAtualizar(), 1, 1 * 60000);
        
        this.setIconImage(new ImageIcon(getClass().getResource("/imagens/final.png")).getImage());
        //ImageIcon icone = new ImageIcon("final.png");
        //setIconImage(icone.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNotas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelTotalLiquido = new javax.swing.JLabel();
        jLabelTotalDescontos = new javax.swing.JLabel();
        jLabelTotalBruto = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelTotalDevolucoes = new javax.swing.JLabel();
        jLabelTotalCancelamentos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldDataFim = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDataInicio = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxVendedores = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jCheckBoxAtualizacao = new javax.swing.JCheckBox();
        jLabelDataAtualizacao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CASAFER - Sistema de gerenciamento de compras e vendas v3.5");
        setMinimumSize(new java.awt.Dimension(903, 516));
        setResizable(false);

        jTableNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serie", "Numero", "Data", "Vendedor", "Total dos Produtos", "Total da Nota", "Valor desconto", "% Desconto", "Situação", "CFOP"
            }
        ));
        jScrollPane1.setViewportView(jTableNotas);
        if (jTableNotas.getColumnModel().getColumnCount() > 0) {
            jTableNotas.getColumnModel().getColumn(0).setMinWidth(50);
            jTableNotas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableNotas.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableNotas.getColumnModel().getColumn(1).setMinWidth(80);
            jTableNotas.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTableNotas.getColumnModel().getColumn(1).setMaxWidth(80);
            jTableNotas.getColumnModel().getColumn(2).setMinWidth(80);
            jTableNotas.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTableNotas.getColumnModel().getColumn(2).setMaxWidth(80);
            jTableNotas.getColumnModel().getColumn(3).setMinWidth(80);
            jTableNotas.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTableNotas.getColumnModel().getColumn(3).setMaxWidth(80);
            jTableNotas.getColumnModel().getColumn(8).setMinWidth(80);
            jTableNotas.getColumnModel().getColumn(8).setPreferredWidth(80);
            jTableNotas.getColumnModel().getColumn(8).setMaxWidth(80);
            jTableNotas.getColumnModel().getColumn(9).setMinWidth(40);
            jTableNotas.getColumnModel().getColumn(9).setPreferredWidth(40);
            jTableNotas.getColumnModel().getColumn(9).setMaxWidth(40);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Total Bruto das Vendas :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Total de Descontos das Vendas :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Total Liquido  : ");
        jLabel9.setToolTipText("(Bruto - Descontos - Devoluções)");

        jLabelTotalLiquido.setBackground(new java.awt.Color(204, 204, 204));
        jLabelTotalLiquido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotalLiquido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabelTotalDescontos.setBackground(new java.awt.Color(204, 204, 204));
        jLabelTotalDescontos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotalDescontos.setForeground(new java.awt.Color(231, 76, 60));
        jLabelTotalDescontos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabelTotalBruto.setBackground(new java.awt.Color(204, 204, 204));
        jLabelTotalBruto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotalBruto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Total devoluções : ");

        jLabelTotalDevolucoes.setBackground(new java.awt.Color(204, 204, 204));
        jLabelTotalDevolucoes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotalDevolucoes.setForeground(new java.awt.Color(231, 76, 60));
        jLabelTotalDevolucoes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabelTotalCancelamentos.setBackground(new java.awt.Color(204, 204, 204));
        jLabelTotalCancelamentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTotalCancelamentos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Total de Cancelamentos : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotalDevolucoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotalBruto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotalDescontos, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotalCancelamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(8, 8, 8)
                        .addComponent(jLabelTotalLiquido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabelTotalBruto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabelTotalDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabelTotalCancelamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabelTotalDevolucoes, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabelTotalLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(471, 158));

        try {
            jTextFieldDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldDataFim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDataFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataFimActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Data fim :");

        try {
            jTextFieldDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldDataInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataInicioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Data inicio :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Vendedor :");

        jComboBoxVendedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxVendedores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(jTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/35834_graph_chart_bar_statistics_poll_icon.png"))); // NOI18N
        jButton3.setText("Grafico Mensal (F8)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/64755_table_chart_icon.png"))); // NOI18N
        jButton2.setText("Comissões (F6)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/35687_arrow_refresh_icon.png"))); // NOI18N
        jButton1.setText("Atualizar (F5)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/64896_total_plan_cost_icon.png"))); // NOI18N
        jButton4.setText("Compras (F7)");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        jCheckBoxAtualizacao.setSelected(true);
        jCheckBoxAtualizacao.setText("Atualização automática    ");
        jToolBar1.add(jCheckBoxAtualizacao);

        jLabelDataAtualizacao.setMaximumSize(new java.awt.Dimension(150, 15));
        jToolBar1.add(jLabelDataAtualizacao);

        jLabel1.setText("Casafer GBM - v2.5");
        jToolBar1.add(jLabel1);

        jMenu1.setText("Opções");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/35687_arrow_refresh_icon.png"))); // NOI18N
        jMenuItem1.setText("Atualizar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/64755_table_chart_icon.png"))); // NOI18N
        jMenuItem2.setText("Comissões");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/64896_total_plan_cost_icon.png"))); // NOI18N
        jMenuItem4.setText("Compras x Vendas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/35834_graph_chart_bar_statistics_poll_icon.png"))); // NOI18N
        jMenuItem3.setText("Grafico Mensal ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        botaoAtualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataInicioActionPerformed

    private void jTextFieldDataFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataFimActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        botaoAtualizar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Comissoes comissoes = new Comissoes(jTextFieldDataInicio.getText(),jTextFieldDataFim.getText());
        comissoes.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Comissoes comissoes = new Comissoes(jTextFieldDataInicio.getText(),jTextFieldDataFim.getText());
        comissoes.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        GraficoMensal graficoMensal = new GraficoMensal();
        graficoMensal.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        GraficoMensal graficoMensal = new GraficoMensal();
        graficoMensal.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaComprasVendas telaComprasVendas = new TelaComprasVendas(jTextFieldDataInicio.getText(),jTextFieldDataFim.getText());
        telaComprasVendas.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TelaComprasVendas telaComprasVendas = new TelaComprasVendas(jTextFieldDataInicio.getText(),jTextFieldDataFim.getText());
        telaComprasVendas.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        GraficoMensal graficoMensal = new GraficoMensal();
        graficoMensal.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBoxAtualizacao;
    private javax.swing.JComboBox jComboBoxVendedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDataAtualizacao;
    private javax.swing.JLabel jLabelTotalBruto;
    private javax.swing.JLabel jLabelTotalCancelamentos;
    private javax.swing.JLabel jLabelTotalDescontos;
    private javax.swing.JLabel jLabelTotalDevolucoes;
    private javax.swing.JLabel jLabelTotalLiquido;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableNotas;
    private javax.swing.JFormattedTextField jTextFieldDataFim;
    private javax.swing.JFormattedTextField jTextFieldDataInicio;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
    public void iniciaTela(){
        jLabelDataAtualizacao.setText(getDateTime());
        jTextFieldDataInicio.setText(getDate());
        jTextFieldDataFim.setText(getDate());
        

        DaoNotasVendas daoNotasVendas = new DaoNotasVendas();
        ArrayList<Vendedores> listaVendedores = new ArrayList();
        
        try {
            listaVendedores = daoNotasVendas.vendedores();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBoxVendedores.removeAllItems();
        jComboBoxVendedores.addItem("Todos");
        for(Vendedores vendedor: listaVendedores){
            jComboBoxVendedores.addItem(vendedor.getVen_Codigo()+ " - " + vendedor.getVen_Nome() );
        }
        
        
    }
    
    public static String formtarDecimal(double saldo) {
    DecimalFormat df = new DecimalFormat("0.00");
    df.setMaximumFractionDigits(2);
    String teste = df.format(saldo);
    return teste;
    }
    public String getDateTime() { 
	SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss"); 
        Date date = new Date();
        return sdf.format(date); 
}
    public String getDate() { 
	SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); 
        Date date = new Date();
        return sdf.format(date); 
}

    private void botaoAtualizar() {
        String temp1 = jTextFieldDataInicio.getText();
        String temp2 = jTextFieldDataFim.getText();
        String temp3 = jComboBoxVendedores.getSelectedItem().toString();
        
        String dataInicio = "";
        String dataFim = "";
        String codVendedor = "";
        
        dataInicio = dataInicio + temp1.substring(6, 10);
        dataInicio = dataInicio + temp1.substring(3, 5);
        dataInicio = dataInicio + temp1.substring(0, 2);
        dataFim = dataFim + temp2.substring(6, 10);
        dataFim = dataFim + temp2.substring(3, 5);
        dataFim = dataFim + temp2.substring(0, 2);

        codVendedor = temp3.substring(0, 2);
        
        
        jLabelDataAtualizacao.setText(getDateTime());
        
        DefaultTableModel model = (DefaultTableModel) jTableNotas.getModel();
        while (jTableNotas.getRowCount() > 0) {
            model.removeRow(0);
        }
        
        ArrayList<NotasVendas> listaNotas = new ArrayList();
        DaoNotasVendas daoNotasVendas = new DaoNotasVendas();
        //se for maior que zero foi selecionado um vendedor        //se for maior que zero foi selecionado um vendedor
        
        if(jComboBoxVendedores.getSelectedIndex() > 0){
            //com vendedor selecionado
            try {
            listaNotas = daoNotasVendas.todasNotasPorVendedor(dataInicio,dataFim,codVendedor);
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            //todos os vendedores
            try {
                listaNotas = daoNotasVendas.todasNotas(dataInicio,dataFim);
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        double totalLiquido = 0;
        double totalBruto = 0;
        double descontos = 0;
        double devolucoes = 0;
        double canceladas = 0;
        for(NotasVendas nota: listaNotas){
            
           model.addRow(new Object[]{nota.getSer_Codigo(), nota.getNF_Numero(), nota.getNF_DataSaida(), nota.getNF_Vendedores(), nota.getNF_VlrMercadorias(),nota.getNF_VlrNota(),nota.getNF_VlrDesc(),nota.getNF_PercDesc(),nota.getNF_Situcao(),nota.getOpFis_Codigo()});
           String tempCFOP = Integer.toString(nota.getOpFis_Codigo());
            String tempDIGITO = tempCFOP.substring(1, 2);
            int digito = Integer.parseInt(tempDIGITO); 
           if(nota.getNF_Situcao().equals("A") && digito == 1 || digito == 4){
                totalLiquido = totalLiquido + nota.getNF_VlrNota();
                totalBruto = totalBruto + nota.getNF_VlrMercadorias();
                descontos = descontos + nota.getNF_VlrDesc();
            }
            if(nota.getNF_Situcao().equals("C")){
                canceladas = canceladas + nota.getNF_VlrNota();
            }
            
            if(digito == 2 && nota.getNF_Situcao().equals("A")){
                devolucoes = devolucoes + nota.getNF_VlrNota();
            }
        }
        double totalLiquidoMenosDev = totalLiquido - devolucoes;
        //mostra totais nos campos
        //jLabelTotalLiquido.setText(formtarDecimal(totalLiquido));
        jLabelTotalLiquido.setText(formtarDecimal(totalLiquidoMenosDev));
        jLabelTotalBruto.setText(formtarDecimal(totalBruto));
        jLabelTotalDescontos.setText("(-) " + formtarDecimal(descontos));
        jLabelTotalCancelamentos.setText(formtarDecimal(canceladas));
        jLabelTotalDevolucoes.setText("(-) " +formtarDecimal(devolucoes));
        
        //CHAMADA DA PINTURA DA TABELA
        jTableNotas.setDefaultRenderer(Object.class, new PintarTabela());

    }
    class botaoAtualizar extends TimerTask {
        
        @Override
        public void run() {
        if(jCheckBoxAtualizacao.isSelected()){
            
           
        String temp1 = jTextFieldDataInicio.getText();
        String temp2 = jTextFieldDataFim.getText();
        String temp3 = jComboBoxVendedores.getSelectedItem().toString();
        
        String dataInicio = "";
        String dataFim = "";
        String codVendedor = "";
        
        dataInicio = dataInicio + temp1.substring(6, 10);
        dataInicio = dataInicio + temp1.substring(3, 5);
        dataInicio = dataInicio + temp1.substring(0, 2);
        
        dataFim = dataFim + temp2.substring(6, 10);
        dataFim = dataFim + temp2.substring(3, 5);
        dataFim = dataFim + temp2.substring(0, 2);

        codVendedor = temp3.substring(0, 2);
        
        jLabelDataAtualizacao.setText(getDateTime());
        
        DefaultTableModel model = (DefaultTableModel) jTableNotas.getModel();
        while (jTableNotas.getRowCount() > 0) {
            model.removeRow(0);
        }
        
        ArrayList<NotasVendas> listaNotas = new ArrayList();
        DaoNotasVendas daoNotasVendas = new DaoNotasVendas();
        //se for maior que zero foi selecionado um vendedor        //se for maior que zero foi selecionado um vendedor
        
        if(jComboBoxVendedores.getSelectedIndex() > 0){
            //com vendedor selecionado
            try {
            listaNotas = daoNotasVendas.todasNotasPorVendedor(dataInicio,dataFim,codVendedor);
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            //todos os vendedores
            try {
                listaNotas = daoNotasVendas.todasNotas(dataInicio,dataFim);
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        double totalLiquido = 0;
        double totalBruto = 0;
        double descontos = 0;
        double devolucoes = 0;
        double canceladas = 0;
        for(NotasVendas nota: listaNotas){
            //1202 é a CFOP de devolucao para dentro do estado
            model.addRow(new Object[]{nota.getSer_Codigo(), nota.getNF_Numero(), nota.getNF_DataSaida(), nota.getNF_Vendedores(), nota.getNF_VlrMercadorias(),nota.getNF_VlrNota(),nota.getNF_VlrDesc(),nota.getNF_PercDesc(),nota.getNF_Situcao(),nota.getOpFis_Codigo()});
            String tempCFOP = Integer.toString(nota.getOpFis_Codigo());
            String tempDIGITO = tempCFOP.substring(1, 2);
            int digito = Integer.parseInt(tempDIGITO);
            if(nota.getNF_Situcao().equals("A") && digito == 1 || digito == 4){
                totalLiquido = totalLiquido + nota.getNF_VlrNota();
                totalBruto = totalBruto + nota.getNF_VlrMercadorias();
                descontos = descontos + nota.getNF_VlrDesc();
            }
            if(nota.getNF_Situcao().equals("C")){
                canceladas = canceladas + nota.getNF_VlrNota();
            }
            
            if(digito == 2 && nota.getNF_Situcao().equals("A")){
                devolucoes = devolucoes + nota.getNF_VlrNota();
            }
        }
        double totalLiquidoMenosDev = totalLiquido - devolucoes;
        //mostra totais nos campos
        //jLabelTotalLiquido.setText(formtarDecimal(totalLiquido));
        jLabelTotalLiquido.setText(formtarDecimal(totalLiquidoMenosDev));
        jLabelTotalBruto.setText(formtarDecimal(totalBruto));
        jLabelTotalDescontos.setText("(-) " + formtarDecimal(descontos));
        jLabelTotalCancelamentos.setText(formtarDecimal(canceladas));
        jLabelTotalDevolucoes.setText("(-) " +formtarDecimal(devolucoes));
        
        //CHAMADA DA PINTURA DA TABELA
        jTableNotas.setDefaultRenderer(Object.class, new PintarTabela());

        }
        }
        
    }
    public class PintarTabela extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); //To change body of generated methods, choose Tools | Templates.
            
            //INICIA AS CORES***************************************************
            Color background = Color.WHITE;
            Color foreground = Color.BLACK;
            
            if(isSelected){
                background = CINZA;
                foreground = Color.WHITE;
            }
            

            //PINTA DESCONTOS***************************************************
            Object objeto = table.getValueAt(row, 7);
            Double valor = Double.parseDouble(objeto.toString());
            
            
            if(valor > 8.00){
                background = AMARELO;
               foreground = Color.WHITE;
            }
            
            
            //PINTA Devolucoes***************************************************
            objeto = table.getValueAt(row, 9);
            int cfop = Integer.parseInt(objeto.toString());
            
            
            if(cfop == 1202){
                background = VERMELHO_ES;
               foreground = Color.WHITE;
            }
            //PINTA NOTAS CANCELADAS********************************************
            
            objeto = table.getValueAt(row, 8);
            String letra = objeto.toString();
            
            if(letra.equals("C")){
               background = VERMELHO;
               foreground = Color.WHITE;
            }
            
            label.setBackground(background);
            label.setForeground(foreground);
        return label;
        }
    }
}

