/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casafer.telas;

import casafer.DaoNotasVendas;
import casafer.NotasCompras;
import casafer.NotasVendas;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bedim
 */
public class TelaComprasVendas extends javax.swing.JFrame {

    /**
     * Creates new form TelaComprasVendas
     */
    public TelaComprasVendas() {
        initComponents();
    }
    public TelaComprasVendas(String dataI,String dataF) {
        initComponents();
        atualizaTela(dataI,dataF);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagens/final.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtVlrTotalMercadoriasNotasCompras = new javax.swing.JTextField();
        txtVlrTotalNotasCompras = new javax.swing.JTextField();
        txtNumeroDeCompras = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtVlrTotalFrete = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtVlrVendasBruto = new javax.swing.JTextField();
        txtVlrDescontosVendas = new javax.swing.JTextField();
        txtVlrDevolucoes = new javax.swing.JTextField();
        txtVlrTotalNotasVendas = new javax.swing.JTextField();
        txtNumeroDeVendas = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtVlrVendasLiquido = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtVlrLiquidoMenosDevolucoes = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtVlrTotalNotasCanceladas = new javax.swing.JTextField();
        txtNumeroNfCanceladas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCompras = new javax.swing.JTable();
        txtDataFinal1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        txtDataInicio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDataFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CASAFER - Analise de compras e vendas v2.5");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(41, 128, 185));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Compras ");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Total Nota : ");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Total Mercadorias : ");

        txtVlrTotalMercadoriasNotasCompras.setEditable(false);
        txtVlrTotalMercadoriasNotasCompras.setBackground(new java.awt.Color(41, 128, 185));
        txtVlrTotalMercadoriasNotasCompras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtVlrTotalMercadoriasNotasCompras.setForeground(new java.awt.Color(255, 255, 255));
        txtVlrTotalMercadoriasNotasCompras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlrTotalMercadoriasNotasCompras.setBorder(null);

        txtVlrTotalNotasCompras.setEditable(false);
        txtVlrTotalNotasCompras.setBackground(new java.awt.Color(41, 128, 185));
        txtVlrTotalNotasCompras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtVlrTotalNotasCompras.setForeground(new java.awt.Color(255, 255, 255));
        txtVlrTotalNotasCompras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlrTotalNotasCompras.setBorder(null);

        txtNumeroDeCompras.setEditable(false);
        txtNumeroDeCompras.setBackground(new java.awt.Color(41, 128, 185));
        txtNumeroDeCompras.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroDeCompras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumeroDeCompras.setBorder(null);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Total Frete : ");

        txtVlrTotalFrete.setEditable(false);
        txtVlrTotalFrete.setBackground(new java.awt.Color(41, 128, 185));
        txtVlrTotalFrete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtVlrTotalFrete.setForeground(new java.awt.Color(255, 255, 255));
        txtVlrTotalFrete.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlrTotalFrete.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumeroDeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(53, 53, 53)
                        .addComponent(txtVlrTotalNotasCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVlrTotalFrete)
                            .addComponent(txtVlrTotalMercadoriasNotasCompras))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumeroDeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtVlrTotalFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtVlrTotalMercadoriasNotasCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtVlrTotalNotasCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(39, 174, 96));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vendas  ");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Descontos :");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Bruto : ");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Devoluções: ");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total : ");

        txtVlrVendasBruto.setEditable(false);
        txtVlrVendasBruto.setBackground(new java.awt.Color(39, 174, 96));
        txtVlrVendasBruto.setForeground(new java.awt.Color(255, 255, 255));
        txtVlrVendasBruto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlrVendasBruto.setBorder(null);

        txtVlrDescontosVendas.setEditable(false);
        txtVlrDescontosVendas.setBackground(new java.awt.Color(39, 174, 96));
        txtVlrDescontosVendas.setForeground(new java.awt.Color(255, 255, 255));
        txtVlrDescontosVendas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlrDescontosVendas.setBorder(null);

        txtVlrDevolucoes.setEditable(false);
        txtVlrDevolucoes.setBackground(new java.awt.Color(39, 174, 96));
        txtVlrDevolucoes.setForeground(new java.awt.Color(255, 255, 255));
        txtVlrDevolucoes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlrDevolucoes.setBorder(null);

        txtVlrTotalNotasVendas.setEditable(false);
        txtVlrTotalNotasVendas.setBackground(new java.awt.Color(39, 174, 96));
        txtVlrTotalNotasVendas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtVlrTotalNotasVendas.setForeground(new java.awt.Color(255, 255, 255));
        txtVlrTotalNotasVendas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlrTotalNotasVendas.setBorder(null);

        txtNumeroDeVendas.setEditable(false);
        txtNumeroDeVendas.setBackground(new java.awt.Color(39, 174, 96));
        txtNumeroDeVendas.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroDeVendas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumeroDeVendas.setBorder(null);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Liquido :");

        txtVlrVendasLiquido.setEditable(false);
        txtVlrVendasLiquido.setBackground(new java.awt.Color(39, 174, 96));
        txtVlrVendasLiquido.setForeground(new java.awt.Color(255, 255, 255));
        txtVlrVendasLiquido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlrVendasLiquido.setBorder(null);

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Liquido - Devoluções: ");

        txtVlrLiquidoMenosDevolucoes.setEditable(false);
        txtVlrLiquidoMenosDevolucoes.setBackground(new java.awt.Color(39, 174, 96));
        txtVlrLiquidoMenosDevolucoes.setForeground(new java.awt.Color(255, 255, 255));
        txtVlrLiquidoMenosDevolucoes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlrLiquidoMenosDevolucoes.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumeroDeVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel20)
                            .addComponent(jLabel14)
                            .addComponent(jLabel21)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVlrTotalNotasVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtVlrLiquidoMenosDevolucoes)
                            .addComponent(txtVlrDevolucoes)
                            .addComponent(txtVlrVendasLiquido)
                            .addComponent(txtVlrDescontosVendas)
                            .addComponent(txtVlrVendasBruto))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNumeroDeVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtVlrVendasBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtVlrDescontosVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtVlrVendasLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtVlrDevolucoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtVlrLiquidoMenosDevolucoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtVlrTotalNotasVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(231, 76, 60));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Vendas Canceladas  ");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total : ");

        txtVlrTotalNotasCanceladas.setEditable(false);
        txtVlrTotalNotasCanceladas.setBackground(new java.awt.Color(231, 76, 60));
        txtVlrTotalNotasCanceladas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtVlrTotalNotasCanceladas.setForeground(new java.awt.Color(255, 255, 255));
        txtVlrTotalNotasCanceladas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVlrTotalNotasCanceladas.setBorder(null);

        txtNumeroNfCanceladas.setEditable(false);
        txtNumeroNfCanceladas.setBackground(new java.awt.Color(231, 76, 60));
        txtNumeroNfCanceladas.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroNfCanceladas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumeroNfCanceladas.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumeroNfCanceladas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(txtVlrTotalNotasCanceladas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtNumeroNfCanceladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtVlrTotalNotasCanceladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTableCompras.setForeground(new java.awt.Color(51, 51, 51));
        jTableCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod Fornecedor", "Fornecedor", "NF_Numero", "Emissao", "Lancamento", "Valor Nota", "Valor Mercadorias", "Valor Frete", "Chave NFe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCompras.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCompras);
        if (jTableCompras.getColumnModel().getColumnCount() > 0) {
            jTableCompras.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableCompras.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTableCompras.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTableCompras.getColumnModel().getColumn(3).setPreferredWidth(60);
            jTableCompras.getColumnModel().getColumn(4).setPreferredWidth(60);
            jTableCompras.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTableCompras.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTableCompras.getColumnModel().getColumn(7).setPreferredWidth(40);
            jTableCompras.getColumnModel().getColumn(8).setPreferredWidth(50);
        }

        txtDataFinal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDataFinal1.setText("Relação de Notas de Compras por Data de Lançamento.");

        jToolBar1.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Periodo   ");
        jToolBar1.add(jLabel1);

        txtDataInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDataInicio.setText("00/00/0000");
        jToolBar1.add(txtDataInicio);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("  -  ");
        jToolBar1.add(jLabel4);

        txtDataFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDataFinal.setText("00/00/0000");
        jToolBar1.add(txtDataFinal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDataFinal1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDataFinal1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComprasVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComprasVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComprasVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComprasVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComprasVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCompras;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel txtDataFinal;
    private javax.swing.JLabel txtDataFinal1;
    private javax.swing.JLabel txtDataInicio;
    private javax.swing.JTextField txtNumeroDeCompras;
    private javax.swing.JTextField txtNumeroDeVendas;
    private javax.swing.JTextField txtNumeroNfCanceladas;
    private javax.swing.JTextField txtVlrDescontosVendas;
    private javax.swing.JTextField txtVlrDevolucoes;
    private javax.swing.JTextField txtVlrLiquidoMenosDevolucoes;
    private javax.swing.JTextField txtVlrTotalFrete;
    private javax.swing.JTextField txtVlrTotalMercadoriasNotasCompras;
    private javax.swing.JTextField txtVlrTotalNotasCanceladas;
    private javax.swing.JTextField txtVlrTotalNotasCompras;
    private javax.swing.JTextField txtVlrTotalNotasVendas;
    private javax.swing.JTextField txtVlrVendasBruto;
    private javax.swing.JTextField txtVlrVendasLiquido;
    // End of variables declaration//GEN-END:variables
    public final void atualizaTela(String temp1,String temp2){
        txtDataInicio.setText(temp1);
        txtDataFinal.setText(temp2);
        DefaultTableModel model = (DefaultTableModel) jTableCompras.getModel();
        while (jTableCompras.getRowCount() > 0) {
            model.removeRow(0);
        }
        DaoNotasVendas daoNotasVendas = new DaoNotasVendas();
        
        String dataInicio = "";
        String dataFim = "";
        dataInicio = dataInicio + temp1.substring(6, 10);
        dataInicio = dataInicio + temp1.substring(3, 5);
        dataInicio = dataInicio + temp1.substring(0, 2);
        dataFim = dataFim + temp2.substring(6, 10);
        dataFim = dataFim + temp2.substring(3, 5);
        dataFim = dataFim + temp2.substring(0, 2);
        
        ArrayList<NotasCompras> listaNotasCompras = new ArrayList();
        
        try {
            listaNotasCompras = daoNotasVendas.todasNotasEntrada(dataInicio, dataFim);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaComprasVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        double totalFrete = 0;
        Double totalNota = 0.0;
        Double totalMercadorias = 0.0;
            for(NotasCompras notas: listaNotasCompras){
                    totalNota = totalNota + notas.getNF_VlrNota();
                    totalFrete = totalFrete + notas.getNF_VlrFrete();
                    totalMercadorias = totalMercadorias + notas.getNF_VlrMercadorias();
                    model.addRow(new Object[]{notas.getFor_Codigo(),notas.getFor_RazaoSocial(), notas.getNF_Numero(), notas.getNF_DataEmissao(), notas.getNF_DataLcto(),notas.getNF_VlrNota(),notas.getNF_VlrMercadorias(),notas.getNF_VlrFrete(),notas.getNF_ChaveNFe()});
            }
            String totalFrete2 = formtarDecimal(totalFrete);
            String totalNota2 = formtarDecimal(totalNota);
            String totalMercadorias2 = formtarDecimal(totalMercadorias);
            txtVlrTotalFrete.setText(totalFrete2);
            txtVlrTotalNotasCompras.setText(totalNota2);
            txtVlrTotalMercadoriasNotasCompras.setText(totalMercadorias2);
            txtNumeroDeCompras.setText(Integer.toString(listaNotasCompras.size()));
            //******************************************************************
            ArrayList<NotasVendas> listaNotasVendas = new ArrayList();
            try {
                listaNotasVendas = daoNotasVendas.todasNotas(dataInicio,dataFim);
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        double totalLiquido = 0;
        double totalBruto = 0;
        double descontos = 0;
        double devolucoes = 0;
        double canceladas = 0;
        int contVendas = 0;
        int contCanceladas = 0;
        for(NotasVendas nota: listaNotasVendas){
            String tempCFOP = Integer.toString(nota.getOpFis_Codigo());
            String tempDIGITO = tempCFOP.substring(1, 2);
            int digito = Integer.parseInt(tempDIGITO); 
           if(nota.getNF_Situcao().equals("A") && digito == 1 || digito ==4){
                totalLiquido = totalLiquido + nota.getNF_VlrNota();
                totalBruto = totalBruto + nota.getNF_VlrMercadorias();
                descontos = descontos + nota.getNF_VlrDesc();
                contVendas++;
            }
            if(nota.getNF_Situcao().equals("C")){
                canceladas = canceladas + nota.getNF_VlrNota();
                contCanceladas++;
            }
            
            if(digito == 2 && nota.getNF_Situcao().equals("A")){
                devolucoes = devolucoes + nota.getNF_VlrNota();
            }
        }
        txtNumeroDeVendas.setText(Integer.toString(contVendas));
        txtNumeroNfCanceladas.setText(Integer.toString(contCanceladas));
        Double liquidoMenosDevolucoes;
        liquidoMenosDevolucoes = totalLiquido - devolucoes;
        txtVlrVendasBruto.setText(formtarDecimal(totalBruto));
        txtVlrDescontosVendas.setText(formtarDecimal(descontos));
        txtVlrVendasLiquido.setText(formtarDecimal(totalLiquido));
        txtVlrDevolucoes.setText(formtarDecimal(devolucoes));
        txtVlrLiquidoMenosDevolucoes.setText(formtarDecimal(liquidoMenosDevolucoes));
        txtVlrTotalNotasCanceladas.setText(formtarDecimal(canceladas));
        txtVlrTotalNotasVendas.setText(formtarDecimal(liquidoMenosDevolucoes));
        
        
        
            
            
    }        
        
    public static String formtarDecimal(double saldo) {
        DecimalFormat df = new DecimalFormat("0.00");
        df.setMaximumFractionDigits(2);
        String teste = df.format(saldo);
        return teste;
    }
}
